# Generated by Django 4.2.5 on 2023-10-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_mfa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mfa_method',
            field=models.CharField(choices=[('TOTP', 'TOTP'), ('SMS', 'SMS')], default='TOTP', max_length=4),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter your phone number in the format: +2348155813450', max_length=15, null=True),
        ),
    ]
