# Generated by Django 4.2.5 on 2023-10-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_mfa', '0003_alter_userprofile_mfa_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='secret_key',
            new_name='totp_secret_key',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='encryption_key',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
